### ISSUE TITLE
Poor style of the website

### ISSUE THREAD

**Issue by Jyothishree2k5** [suyash-thakur/js-good-first-issues-finder#13]
I made this website a bit good looking by modifying the css in the styles.css file. Please give this issue to me.
This is how it looks, which is kind of better that the before one. I am a beginner and would like to contribute more.
![Screenshot 2024-08-25 131448](https://github.com/user-attachments/assets/1f0e0cad-e05d-412f-a59a-8fbc71168aae)

**Comment by suyash-thakur** [comment]
Hey @Jyothishree2k5 . I have assigned the issue to you

**Comment by AtharvaGurao** [comment]
Subject: Request for Access to Issue #13 (Poor Style of the Website)

Dear Suyash-thakur,

I hope you're doing well. I have been following the project and noticed Issue #13, "Poor style of the website." I have worked on an improved style for the website and would love to contribute to resolving this issue.

Could you please grant me access to the issue so that I can share the updated design and collaborate on enhancing the website's style?

Looking forward to your response.

Thank you for your time and consideration!

Best regards,
Atharva Gurao
<img width="1436" alt="Screenshot 2024-09-25 at 11 02 34 PM" src="https://github.com/user-attachments/assets/fe2432a6-cb97-4ad0-845d-dabe4112f130">

**Comment by suyash-thakur** [comment]
Hey @AtharvaGurao . I have added some comments to you'r PR

**Comment by AbhiSharmaNIT** [comment]
I want to work on this website pls assign me. Even I can build this dynamic.

**Comment by suyash-thakur** [comment]
Hey guys !! This issue is closed by [this PR](https://github.com/suyash-thakur/js-good-first-issues-finder/pull/19) thanks to @AtharvaGurao. If you still want to contribute to the repo you can pick other open issues or if you can create a better styling for the website you can create a PR independently. Thanks
